//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apadana.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apadana.Entities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلیه مشاغل , مهارت ها و تخصص ها به صورت کلمات کلیدی.
        /// </summary>
        public static string DisName_AboutSpeciality {
            get {
                return ResourceManager.GetString("DisName_AboutSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string DisName_Address {
            get {
                return ResourceManager.GetString("DisName_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت اعتبار آگهی.
        /// </summary>
        public static string DisName_AdsValidityPeriod {
            get {
                return ResourceManager.GetString("DisName_AdsValidityPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست دهنده.
        /// </summary>
        public static string DisName_Applicant {
            get {
                return ResourceManager.GetString("DisName_Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string DisName_Birthdate {
            get {
                return ResourceManager.GetString("DisName_Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string DisName_City {
            get {
                return ResourceManager.GetString("DisName_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر فارغ التحصیلی.
        /// </summary>
        public static string DisName_CityOfDegree {
            get {
                return ResourceManager.GetString("DisName_CityOfDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string DisName_Count {
            get {
                return ResourceManager.GetString("DisName_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات مهارت ها و تخصص ها.
        /// </summary>
        public static string DisName_DescriptionForSpeciality {
            get {
                return ResourceManager.GetString("DisName_DescriptionForSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string DisName_Email {
            get {
                return ResourceManager.GetString("DisName_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string DisName_FatherName {
            get {
                return ResourceManager.GetString("DisName_FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمینه فعالیت.
        /// </summary>
        public static string DisName_FieldOfAcivity {
            get {
                return ResourceManager.GetString("DisName_FieldOfAcivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی.
        /// </summary>
        public static string DisName_FieldOfStudy {
            get {
                return ResourceManager.GetString("DisName_FieldOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string DisName_Gender {
            get {
                return ResourceManager.GetString("DisName_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل.
        /// </summary>
        public static string DisName_GradePointAverage {
            get {
                return ResourceManager.GetString("DisName_GradePointAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس.
        /// </summary>
        public static string DisName_HasService {
            get {
                return ResourceManager.GetString("DisName_HasService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسئول واحد.
        /// </summary>
        public static string DisName_HeadOfTheUnit {
            get {
                return ResourceManager.GetString("DisName_HeadOfTheUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت بیمه.
        /// </summary>
        public static string DisName_InsuranceStatus {
            get {
                return ResourceManager.GetString("DisName_InsuranceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان شغلی.
        /// </summary>
        public static string DisName_JobTitle {
            get {
                return ResourceManager.GetString("DisName_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string DisName_LastName {
            get {
                return ResourceManager.GetString("DisName_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مدرک تحصیلی.
        /// </summary>
        public static string DisName_LatestDegree {
            get {
                return ResourceManager.GetString("DisName_LatestDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تاهل.
        /// </summary>
        public static string DisName_MaritalStatus {
            get {
                return ResourceManager.GetString("DisName_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر سن.
        /// </summary>
        public static string DisName_MaxAge {
            get {
                return ResourceManager.GetString("DisName_MaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت خدمت.
        /// </summary>
        public static string DisName_MilitaryStatus {
            get {
                return ResourceManager.GetString("DisName_MilitaryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تحصیلات.
        /// </summary>
        public static string DisName_MinimumEducation {
            get {
                return ResourceManager.GetString("DisName_MinimumEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مدت سابقه كار در حوزه تحصيلات يا مهارت تخصصي.
        /// </summary>
        public static string DisName_MinimumRelatedExperience {
            get {
                return ResourceManager.GetString("DisName_MinimumRelatedExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string DisName_Mobile {
            get {
                return ResourceManager.GetString("DisName_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string DisName_Name {
            get {
                return ResourceManager.GetString("DisName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی.
        /// </summary>
        public static string DisName_NationalCode {
            get {
                return ResourceManager.GetString("DisName_NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string DisName_OrganizationBeginDate {
            get {
                return ResourceManager.GetString("DisName_OrganizationBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان.
        /// </summary>
        public static string DisName_OrganizationEndDate {
            get {
                return ResourceManager.GetString("DisName_OrganizationEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمینه فعالیت سازمان.
        /// </summary>
        public static string DisName_OrganizationFieldOfActivity {
            get {
                return ResourceManager.GetString("DisName_OrganizationFieldOfActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان و سمت شغلی.
        /// </summary>
        public static string DisName_OrganizationJobTitle {
            get {
                return ResourceManager.GetString("DisName_OrganizationJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سازمان.
        /// </summary>
        public static string DisName_OrganizationName {
            get {
                return ResourceManager.GetString("DisName_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علت ترک شغل.
        /// </summary>
        public static string DisName_OrganizationReasonForLeave {
            get {
                return ResourceManager.GetString("DisName_OrganizationReasonForLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسنامه.
        /// </summary>
        public static string DisName_PersonalId {
            get {
                return ResourceManager.GetString("DisName_PersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string DisName_Phone {
            get {
                return ResourceManager.GetString("DisName_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string DisName_Province {
            get {
                return ResourceManager.GetString("DisName_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقه کار مرتبط.
        /// </summary>
        public static string DisName_RelatedWorkExperience {
            get {
                return ResourceManager.GetString("DisName_RelatedWorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان حقوق.
        /// </summary>
        public static string DisName_Salary {
            get {
                return ResourceManager.GetString("DisName_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات سرویس.
        /// </summary>
        public static string DisName_ServiceDescription {
            get {
                return ResourceManager.GetString("DisName_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام واحد.
        /// </summary>
        public static string DisName_UnitName {
            get {
                return ResourceManager.GetString("DisName_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دانشگاه.
        /// </summary>
        public static string DisName_UniversityName {
            get {
                return ResourceManager.GetString("DisName_UniversityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دانشگاه.
        /// </summary>
        public static string DisName_UniversityType {
            get {
                return ResourceManager.GetString("DisName_UniversityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string DisName_UserName {
            get {
                return ResourceManager.GetString("DisName_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات کاری.
        /// </summary>
        public static string DisName_WorkingHours {
            get {
                return ResourceManager.GetString("DisName_WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال فارغ التحصیلی.
        /// </summary>
        public static string DisName_YearOfGraduation {
            get {
                return ResourceManager.GetString("DisName_YearOfGraduation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} و {1} یکسان نیستند.
        /// </summary>
        public static string Val_confirm_is_not_the_same {
            get {
                return ResourceManager.GetString("Val_confirm_is_not_the_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید بین {0} و {1} باشد.
        /// </summary>
        public static string Val_enter_a_valid_number {
            get {
                return ResourceManager.GetString("Val_enter_a_valid_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} اجباری است.
        /// </summary>
        public static string Val_this_field_is_required {
            get {
                return ResourceManager.GetString("Val_this_field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} غیر قابل قبول است.
        /// </summary>
        public static string Val_wrong_type {
            get {
                return ResourceManager.GetString("Val_wrong_type", resourceCulture);
            }
        }
    }
}
